<<<<<<< HEAD
# Generated by Django 2.0.2 on 2020-02-18 21:01
=======
# Generated by Django 2.2.2 on 2020-02-17 11:11
>>>>>>> 01b223460a761091531d1b4af2d88e5599152d32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HOD',
            fields=[
                ('email', models.CharField(default=None, max_length=100, primary_key=True, serialize=False)),
                ('password', models.CharField(default=None, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Minister',
            fields=[
                ('email', models.CharField(default=None, max_length=100, primary_key=True, serialize=False)),
                ('password', models.CharField(default=None, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
<<<<<<< HEAD
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_number', models.CharField(default='0', max_length=100, null=True)),
                ('ip_number', models.CharField(default='0', max_length=100, null=True)),
=======
                ('mobile_number', models.CharField(default=0, max_length=100, primary_key=True, serialize=False)),
>>>>>>> 01b223460a761091531d1b4af2d88e5599152d32
                ('Rating', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('sandf', models.CharField(default=None, max_length=50, null=True)),
                ('department', models.CharField(default=None, max_length=50, null=True)),
                ('AreaofIssue', models.CharField(blank=True, default=None, max_length=40, null=True)),
                ('Hygiene', models.CharField(blank=True, default=None, max_length=5, null=True)),
                ('DoctorBehaviour', models.CharField(blank=True, default=None, max_length=5, null=True)),
                ('WaitingTime', models.CharField(blank=True, default=None, max_length=5, null=True)),
                ('Pharmacy', models.CharField(blank=True, default=None, max_length=5, null=True)),
                ('Nurse', models.CharField(blank=True, default=None, max_length=5, null=True)),
                ('explanation', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('Status', models.CharField(blank=True, default='0', max_length=10, null=True)),
                ('otp', models.CharField(blank=True, default=None, max_length=6, null=True)),
<<<<<<< HEAD
=======
                ('voice_record', models.FileField(default='goodfile.txt', upload_to='')),
>>>>>>> 01b223460a761091531d1b4af2d88e5599152d32
            ],
        ),
        migrations.CreateModel(
            name='PatientIN',
            fields=[
<<<<<<< HEAD
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_number', models.CharField(default='0', max_length=100)),
                ('ip_number', models.CharField(default='0', max_length=100)),
                ('Rating', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('sandf', models.CharField(default=None, max_length=50, null=True)),
                ('department', models.CharField(default=None, max_length=50, null=True)),
                ('AreaofIssue', models.CharField(blank=True, default=None, max_length=40, null=True)),
=======
                ('mobile_number', models.CharField(default=0, max_length=100, primary_key=True, serialize=False)),
                ('Rating', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('sandf', models.CharField(default=None, max_length=50, null=True)),
                ('department', models.CharField(default=None, max_length=50, null=True)),
                ('AreaofIssue', models.CharField(blank=True, default=None, max_length=50, null=True)),
>>>>>>> 01b223460a761091531d1b4af2d88e5599152d32
                ('AdmissionIssue', models.CharField(blank=True, default=None, max_length=40, null=True)),
                ('NurseIssue', models.CharField(blank=True, default=None, max_length=40, null=True)),
                ('DoctorIssue', models.CharField(blank=True, default=None, max_length=40, null=True)),
                ('AllotmentIssue', models.CharField(blank=True, default=None, max_length=40, null=True)),
                ('DischargeIssue', models.CharField(blank=True, default=None, max_length=40, null=True)),
                ('explanation', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('Status', models.CharField(blank=True, default='0', max_length=10, null=True)),
                ('otp', models.CharField(blank=True, default=None, max_length=6, null=True)),
            ],
        ),
    ]
