# Generated by Django 2.2.2 on 2020-02-15 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HOD',
            fields=[
                ('email', models.CharField(default=None, max_length=100, primary_key=True, serialize=False)),
                ('password', models.CharField(default=None, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('mobile_number', models.CharField(default=0, max_length=10, primary_key=True, serialize=False)),
                ('Rating', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('sandf', models.CharField(default=None, max_length=50, null=True)),
                ('department', models.CharField(default=None, max_length=50, null=True)),
                ('AreaofIssue', models.CharField(blank=True, default=None, max_length=4, null=True)),
                ('explanation', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('recording', models.CharField(blank=True, default='0', max_length=2, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PatientIN',
            fields=[
                ('mobile_number', models.CharField(default=0, max_length=10, primary_key=True, serialize=False)),
                ('Rating', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('sandf', models.CharField(default=None, max_length=50, null=True)),
                ('department', models.CharField(default=None, max_length=50, null=True)),
                ('AreaofIssue', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('explanation', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('recording', models.CharField(blank=True, default='0', max_length=2, null=True)),
            ],
        ),
    ]
