# Generated by Django 2.0.2 on 2020-02-18 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Feedback', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='ip_number',
            field=models.CharField(default='0', max_length=101, null=True),
        ),
    ]
