# Generated by Django 2.2.2 on 2020-02-17 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Feedback', '0002_auto_20200217_1703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='voice_record',
        ),
    ]
