# Generated by Django 2.0.2 on 2020-02-18 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Feedback', '0002_auto_20200219_0238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientin',
            name='ip_number',
            field=models.CharField(default='0', max_length=101),
        ),
    ]
