# Generated by Django 2.2.2 on 2020-02-15 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Feedback', '0002_auto_20200215_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientin',
            name='AdmissionIssue',
            field=models.CharField(blank=True, default=None, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='patientin',
            name='AllotmentIssue',
            field=models.CharField(blank=True, default=None, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='patientin',
            name='DischargeIssue',
            field=models.CharField(blank=True, default=None, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='patientin',
            name='DoctorIssue',
            field=models.CharField(blank=True, default=None, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='patientin',
            name='NurseIssue',
            field=models.CharField(blank=True, default=None, max_length=40, null=True),
        ),
    ]
