# Generated by Django 2.2.2 on 2020-02-15 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Feedback', '0003_auto_20200215_1617'),
    ]

    operations = [
        migrations.CreateModel(
            name='testing',
            fields=[
                ('email_id', models.CharField(default=None, max_length=50, primary_key=True, serialize=False)),
                ('otp', models.CharField(default=None, max_length=6)),
            ],
        ),
        migrations.AlterField(
            model_name='patient',
            name='mobile_number',
            field=models.CharField(default=0, max_length=100, primary_key=True, serialize=False),
        ),
    ]
