# Generated by Django 2.2.2 on 2020-02-17 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Feedback', '0003_remove_patient_voice_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='voice_record',
            field=models.FileField(default='', upload_to=''),
        ),
        migrations.AddField(
            model_name='patientin',
            name='voice_record',
            field=models.FileField(default='', upload_to=''),
        ),
        migrations.AlterField(
            model_name='patientin',
            name='AreaofIssue',
            field=models.CharField(blank=True, default=None, max_length=40, null=True),
        ),
    ]
