# Generated by Django 2.2.2 on 2020-02-15 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Feedback', '0004_auto_20200215_2002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='recording',
        ),
        migrations.RemoveField(
            model_name='patientin',
            name='recording',
        ),
        migrations.AddField(
            model_name='patient',
            name='DoctorBehaviour',
            field=models.CharField(blank=True, default=None, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='Hygiene',
            field=models.CharField(blank=True, default=None, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='Nurse',
            field=models.CharField(blank=True, default=None, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='Pharmacy',
            field=models.CharField(blank=True, default=None, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='WaitingTime',
            field=models.CharField(blank=True, default=None, max_length=5, null=True),
        ),
    ]
