# Generated by Django 2.2.2 on 2020-02-15 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Feedback', '0005_auto_20200216_0243'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='Status',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
    ]
