# Generated by Django 2.2.2 on 2020-02-16 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Feedback', '0006_patient_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientin',
            name='mobile_number',
            field=models.CharField(default=0, max_length=100, primary_key=True, serialize=False),
        ),
    ]
