# Generated by Django 2.2.2 on 2020-02-16 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Feedback', '0007_auto_20200216_0751'),
    ]

    operations = [
        migrations.DeleteModel(
            name='testing',
        ),
        migrations.AddField(
            model_name='patient',
            name='otp',
            field=models.CharField(blank=True, default=None, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='patientin',
            name='otp',
            field=models.CharField(blank=True, default=None, max_length=6, null=True),
        ),
    ]
