# Generated by Django 2.2.2 on 2020-02-16 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Feedback', '0008_auto_20200216_0907'),
    ]

    operations = [
        migrations.CreateModel(
            name='testing',
            fields=[
                ('email_id', models.CharField(default=None, max_length=50, primary_key=True, serialize=False)),
                ('otp', models.CharField(default=None, max_length=6)),
            ],
        ),
    ]
