# Generated by Django 2.2.2 on 2020-02-16 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Feedback', '0009_testing'),
    ]

    operations = [
        migrations.DeleteModel(
            name='testing',
        ),
    ]
