# Generated by Django 2.2.2 on 2020-02-16 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Feedback', '0010_delete_testing'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientin',
            name='Status',
            field=models.CharField(blank=True, default='0', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='Status',
            field=models.CharField(blank=True, default='0', max_length=10, null=True),
        ),
    ]
