# Generated by Django 2.2.2 on 2020-02-17 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Feedback', '0011_auto_20200216_1245'),
    ]

    operations = [
        migrations.CreateModel(
            name='Minister',
            fields=[
                ('email', models.CharField(default=None, max_length=100, primary_key=True, serialize=False)),
                ('password', models.CharField(default=None, max_length=20)),
            ],
        ),
    ]
